# Generated by Django 4.1 on 2022-08-16 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure', models.TimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=100)),
                ('medecin_traitant', models.CharField(choices=[(' ', ' '), ('RAMAVONIRINA Tantely', 'RAMAVONIRINA Tantely'), ('NIRINA Sylvianne', 'NIRINA Sylvianne')], default=' ', max_length=100)),
                ('service', models.CharField(choices=[('', ' '), ('ORL', 'ORL'), ('PPH', 'PPH'), ('Pédiatrie', 'Pédiatrie'), ('Chirurgie', 'Chirurgie'), ('Gynécologie', 'Gynécologie'), ('Laboratoire', 'Laboratoire'), ('Dermatologie', 'Dermatologie'), ('Radiographie', 'Radiographie'), ('Ophtalmologie', 'Ophtalmologie'), ('Neuropsychatrie', 'Neuropsychatrie')], default=' ', max_length=100)),
                ('frais', models.CharField(choices=[(' ', ' '), ('Non payé', 'Non payé'), ('Payé à moitié', 'Payé à moitié'), ('Payé en entier', 'Payé en entier')], default=' ', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[(' ', ' '), ('Féminin', 'Féminin'), ('Masculin', 'Masculin')], default=' ', max_length=10)),
                ('date_de_naissance', models.DateField(default=django.utils.timezone.now)),
                ('lieu_de_naissance', models.CharField(max_length=100)),
                ('groupe_sanguin', models.CharField(choices=[(' ', ' '), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=' ', max_length=10)),
                ('medecin_traitant', models.CharField(choices=[(' ', ' '), ('RAMAVONIRINA Tantely', 'RAMAVONIRINA Tantely'), ('NIRINA Sylvianne', 'NIRINA Sylvianne')], default=' ', max_length=100)),
            ],
        ),
    ]
